---
title: "Borda Count"
author: "Jordan Fan"
date: "October 1, 2017"
output: html_document
---


## Borda Count Algorithm 


```{r Borda Count Function}

borda <- function(data){
  data = as.matrix(data)
  rankings = t(apply(data, 1, rank))
  #ranks each candidate for each row, then transposes the rankings so that all the ranks of each candidate are in the same column 
  sum_ranks = colSums(rankings)
  index = which(colSums(rankings) == max(colSums(rankings)))
  if (length(index) == 1){
    }
  else {
      index = sample(index, 1)
      #if there is a tie, choose candidate randomly
    }
  return(colnames(data)[index]) 
}
```

```{r}
borda_strategic = function(data, percent){
  if (percent == 0){
    return (borda(data))
  }
  df = data 
  samples = sample(nrow(data), floor(nrow(data) * percent))
  strategic_voters = df[samples,]
  df = df[-samples,]
  pivots = pivot_prob(miu, colnames(data))
  strategic_voter_ratings = t(apply(as.matrix(strategic_voters), 1, best_candidate, pivots = pivots))
  colnames(strategic_voter_ratings) = colnames(df)
  df = rbind(df, strategic_voter_ratings)
  borda(df)
}
borda_strategic(data, 0)
```

```{r}
borda_strategic_votes = function(candidate, m, percent){
  n_cand = length(candidate)
  miu = matrix(sample(-100:100, m * n_cand, replace = TRUE), ncol = n_cand)
  theta = matrix(sample(0:100, m * n_cand, replace = TRUE), ncol = n_cand)
  df = data.frame(mapply(data_generator, miu, theta, candidate = candidate, n = m))
  #create a large dataframe, each column contains simulated data from a specific normal curve with mean miu and sd theta 
  m_function = function(x) { 
    arr = rep(n_cand, n_cand)
    decrease = c((n_cand - 1):0)
    data.frame(df[, arr * x - decrease]) 
  }
  dataset = lapply(1:(ncol(df)/n_cand), m_function)
  strategic_borda_results = mapply(winner_satisfaction_popular, dataset, lapply(dataset, borda_strategic, percent = percent))[2,]
  sum(strategic_borda_results)/m
}

borda_strategic_votes(c("a","b","c"), 100, .2) 
```

```{r}
borda_strategic_CI_3_25 = replicate(1000, borda_strategic_votes(c("a", "b","c"), 100, .25))
borda_strategic_CI_4_25 = replicate(1000, borda_strategic_votes(c("a", "b","c", "d"), 100, .25))
borda_strategic_CI_5_25 = replicate(1000, borda_strategic_votes(c("a", "b","c","d","e"), 100, .25))
```

```{r}
borda_strategic_CI_3_50 = replicate(1000, borda_strategic_votes(c("a", "b","c"), 100, .5))
borda_strategic_CI_4_50 = replicate(1000, borda_strategic_votes(c("a", "b","c", "d"), 100, .5))
borda_strategic_CI_5_50 = replicate(1000, borda_strategic_votes(c("a", "b","c","d","e"), 100, .5))
borda_strategic_CI_3_0 = replicate(1000, borda_strategic_votes(c("a", "b","c"), 100, 0))
borda_strategic_CI_4_0 = replicate(1000, borda_strategic_votes(c("a", "b","c", "d"), 100, 0))
borda_strategic_CI_5_0 = replicate(1000, borda_strategic_votes(c("a", "b","c","d","e"), 100, 0))
```

```{r}
library(ggplot2)
strategic_percentages = factor(c(rep("0%", length(borda_strategic_CI_3_0)), rep("25%", length(borda_strategic_CI_3_25)), rep("50%", length(borda_strategic_CI_3_50))))
accuracy = c(borda_strategic_CI_3_0, borda_strategic_CI_3_25, borda_strategic_CI_3_50)
strategic_borda_3_cands = data.frame(percent_strategic = strategic_percentages, accuracy = accuracy)
ggplot(strategic_borda_3_cands, aes(x = percent_strategic, y = accuracy, fill = percent_strategic)) + geom_boxplot()
```

```{r}
summary_3_cands = data.frame("0%" = as.numeric(summary(borda_strategic_CI_3_0)), "25%" = as.numeric(summary(borda_strategic_CI_3_25)), "50%" = as.numeric(summary(borda_strategic_CI_3_50)))
rownames(summary_3_cands) = c("min", "1st quartile", "median", "mean", "3rd quartile", "max")
summary_3_cands
```

```{r}
accuracy_4 = c(borda_strategic_CI_4_0, borda_strategic_CI_4_25, borda_strategic_CI_4_50)
strategic_borda_4_cands = data.frame(percent_strategic = strategic_percentages, accuracy = accuracy_4)
ggplot(strategic_borda_4_cands, aes(x = percent_strategic, y = accuracy, fill = percent_strategic)) + geom_boxplot()
```

```{r}
summary_4_cands = data.frame("0%" = as.numeric(summary(borda_strategic_CI_4_0)), "25%" = as.numeric(summary(borda_strategic_CI_4_25)), "50%" = as.numeric(summary(borda_strategic_CI_4_50)))
rownames(summary_4_cands) = c("min", "1st quartile", "median", "mean", "3rd quartile", "max")
summary_4_cands
```

```{r}
accuracy_5 = c(borda_strategic_CI_5_0, borda_strategic_CI_5_25, borda_strategic_CI_5_50)
strategic_borda_5_cands = data.frame(percent_strategic = strategic_percentages, accuracy = accuracy_5)
ggplot(strategic_borda_5_cands, aes(x = percent_strategic, y = accuracy, fill = percent_strategic)) + geom_boxplot()
```

```{r}
summary_5_cands = data.frame("0%" = as.numeric(summary(borda_strategic_CI_5_0)), "25%" = as.numeric(summary(borda_strategic_CI_5_25)), "50%" = as.numeric(summary(borda_strategic_CI_5_50)))
# rownames(summary_5_cands) = c("min", "1st quartile", "median", "mean", "3rd quartile", "max")
summary_5_cands
```

